export enum Gender {
  M = "M",
  F = "F",
}

export enum GoalPeriod {
  WITHIN_1_YEAR = "WITHIN_1_YEAR",
  WITHIN_3_YEARS = "WITHIN_3_YEARS",
  WITHIN_5_YEARS = "WITHIN_5_YEARS",
  MORE_THAN_5_YEARS = "MORE_THAN_5_YEARS",
}

export enum GoalType {
  HOUSE = "HOUSE",
  LUMPSUM = "LUMPSUM",
  RETIREMENT = "RETIREMENT",
  MARRIAGE = "MARRIAGE",
}

export enum InvestmentType {
  CONSERVATIVE = "CONSERVATIVE",
  MODERATE = "MODERATE",
  NEUTRAL = "NEUTRAL",
  AGGRESSIVE = "AGGRESSIVE",
  VERY_AGGRESSIVE = "VERY_AGGRESSIVE",
}

export enum ProductCategory {
  SAVINGS = "SAVINGS",
  CASH = "CASH",
  DOMESTIC_STOCKS = "DOMESTIC_STOCKS",
  DEVELOPED_STOCKS = "DEVELOPED_STOCKS",
  EMERGING_STOCKS = "EMERGING_STOCKS",
  DOMESTIC_BONDS = "DOMESTIC_BONDS",
  FOREIGN_BONDS = "FOREIGN_BONDS",
  ALTERNATIVE = "ALTERNATIVE",
}

export enum RiskLevel {
  VERY_LOW = "VERY_LOW",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  LITTLE_HIGH = "LITTLE_HIGH",
  HIGH = "HIGH",
  VERY_HIGH = "VERY_HIGH",
}

export enum IdealIncomeRange {
  NEAR_400 = "NEAR_400",
  NEAR_600 = "NEAR_600",
  NEAR_800 = "NEAR_800",
  OVER_1000 = "OVER_1000",
}
